parameters:
  - name: vmImage
    type: string
    default: ubuntu-latest

stages:
  - stage: lint_and_tests
    pool:
      vmImage: ${{ parameters.vmImage }}
    condition: eq(variables['Build.Reason'], 'PullRequest')
    displayName: Lint, tests and code quality
    jobs:
      - template: ./jobs-lint-and-build.yaml
