parameters:
  - name: vmImage
    type: string
    default: ubuntu-latest

stages:
  - stage: lint_and_tests
    pool:
      vmImage: ${{ parameters.vmImage }}
    condition: eq(variables['Build.Reason'], 'PullRequest')
    displayName: Lint, tests and code quality
    jobs:
      - template: ./jobs-lint-and-build.yaml

  - stage: build
    pool:
      vmImage: ${{ parameters.vmImage }}
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: Build and publish artifacts
    jobs:
      - template: ./jobs-build-and-publish-artifacts.yaml

  - stage: deploy
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: build
    displayName: Deploy to AWS
    jobs:
      - template: ./jobs-deploy-to-aws.yaml
        parameters:
          BucketName: 'my-spa-bucket-justfortest'
