parameters:
  - name: BucketName
    type: string
    default: ''
  - name: EnvironmentName
    type: string

jobs:
  - deployment: deploy
    environment: ${{ parameters.EnvironmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AWSCLI@1
              inputs:
                awsCredentials: 'YOUR_AWS_CONNECTION'
                regionName: 'us-east-1'
                awsCommand: 's3'
                awsSubCommand: 'sync'
                awsArguments: '$(System.DefaultWorkingDirectory)/drop s3://${{ parameters.BucketName }} --delete'
