jobs:
  - job: lint
    variables:
      - name: YARN_CACHE_FOLDER
        value: $(Pipeline.Workspace)/.yarn
    displayName: 'Lint & tests'
    steps:
      - template: ./steps-install-packages.yaml

      - script: |
          yarn build && yarn test:ci
        displayName: 'Build & tests'
