jobs:
  - job: build
    displayName: 'Build'
    steps:
      - template: ./steps-install-packages.yaml
        parameters:
          CachePackageInstall: false

      - script: |
          yarn build
        displayName: 'Build'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: dist/
