parameters:
  - name: BucketName
    type: string
    default: ''

jobs:
  - job: deploy
    displayName: 'Deploy'
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: AWSCLI@1
        inputs:
          awsCredentials: 'YOUR_AWS_CONNECTION'
          regionName: 'us-east-1'
          awsCommand: 's3'
          awsSubCommand: 'sync $(System.ArtifactsDirectory)/drop s3://${{ parameters.BucketName }}'
          awsArguments: '--delete'
