variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: lint
    displayName: 'Lint & tests'
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 16.x'
        inputs:
          versionSpec: '16.x'

      - task: Cache@2
        inputs:
          key: '"yarn" | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            "yarn" | "$(Agent.OS)"
            "yarn"
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: |
          yarn --frozen-lockfile
        displayName: 'Yarn install'

      - script: |
          yarn build && yarn test:ci
        displayName: 'Build & tests'
