jobs:
  - job: lint
    variables:
      - name: YARN_CACHE_FOLDER
        value: $(Pipeline.Workspace)/.yarn
    displayName: 'Run build and tests'
    steps:
      - template: ./steps-install-packages.yaml

      - script: |
          set -e
          echo variables['Build.Reason']
          echo $(Build.Reason)

      - script: |
          yarn build && yarn test:ci
        displayName: 'Build & tests'
